# Generated by Django 2.2.1 on 2019-06-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runaway', '0004_auto_20190613_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
