# Generated by Django 2.2.1 on 2019-06-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runaway', '0005_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
