# Generated by Django 2.2.1 on 2019-06-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runaway', '0006_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='residence',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
