# Generated by Django 2.2.1 on 2019-06-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runaway', '0008_auto_20190618_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(null=True),
        ),
    ]
