# Generated by Django 2.2.1 on 2019-06-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runaway', '0011_auto_20190619_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='lng',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
    ]
